### ISSUE TITLE
struct_pb

### ISSUE THREAD

**Issue by kcjkcj3054** [alibaba/yalantinglibs#546]
I am analyzing struct_pb, and I understand that yalantinglibs is header-only, and adding the header uses the corresponding library functions.
1. Is struct_pb an exception?

2. https://alibaba.github.io/yalantinglibs/en/struct_pb/struct_pb_generating_your_struct.html If you look here, you have to do it in that order to create a solution file, but if you do Hedo Only, can you skip that process? Or is probuf gen absolutely necessary??

3. The explanation explains Mac and Ubuntu well, but it doesn't explain Windows well. Could you please explain a little more kindly about Windows, starting with seconds?

Thank you always

Is it possible to serialize and deserialize with header only, without using the .proto file?
This seems to be struct_pack, but...

Maybe the .proto is in a different file and my solution doesn't use .proto, so is it possible to deserialize that file?

**Comment by PikachuHyA** [comment]
Thank you for your question.

When I developed the first version of struct_pb, it was header-only. However, this version had a significant flaw: the compilation speed was too slow. The second version adopted a code generation approach (which is the current version). By implementing a plugin for protoc, it generates the serialization and deserialization code for struct_pb. **At present, this version is still experimental and not production-ready (may still lots of BUG).** I believe I have now fully answered your first question. Regarding your second question, since the current version requires code generation, this process is necessary. As for your third question, I do not have a Windows machine, so all development and testing have been carried out on Mac and Linux. Logically, the process is the same: first use the protoc plugin to code-generate the respective struct_pb code, and then use it directly.

Thank you again for your interest in struct_pb.

**Comment by kcjkcj3054** [comment]
Thank you so much for the detailed answer. I understood most of it. I don't have much experience with protoc in C++, and I installed it a few years ago, so there are a lot of confusing parts.

After installing the current protoc, I set the environment variables, checked protoc --version in cmd, and installed protoc from vcpkg.

But what I'm curious about is
Use the protoc plugin to code-generate the corresponding struct_pb code and then use it directly. This part is protoc --plugin=protoc-gen-struct_pb --struct_pb_out. xxx.proto
Is this correct?

Open cmd where .proto exists and then type protoc --plugin=protoc-gen-struct_pb --struct_pb_out. I asked a question because an error occurred when running addressbook.proto.

@PikachuHyA PikachuHyA

**Comment by PikachuHyA** [comment]
sorry for late reply

> Use the protoc plugin to code-generate the corresponding struct_pb code and then use it directly. This part is protoc --plugin=protoc-gen-struct_pb --struct_pb_out. xxx.proto

yes.

> problems can also occur with the current code generation method?

the codegen part is functioning correctly.
the BUG may in handing unknown data (e.g. due to `.proto` change, some fields missing)

> Should I run the command within the proto-plugin folder, but set the location of xxx.proto to proto?

If `protoc --struct_pb_out . xxx.proto` runs normally, then using the struct_pb plugin at that location should work properly. It should be noted that the parameter for `--plugin` needs to specify the path to the `protoc-gen-struct_pb` binary file.

> where the protoc-gen-struct_pb file exists

if you in the build path, the `protoc-gen-struct_pb` is in `output/bin/protoc-gen-struct_pb`

> with the current code generation method, would it be more stable to use the existing protobuffer?

because it hasn't been validated on a large scale online product, we cannot conclude that it's better than protobuf. The motivation for doing struct_pb is that we hope the same set of structure definitions (e.g. UserInfo, Item) can be serialized and deserialized by struct_pack, as well as be serialized and deserialized to and from the protobuf format. 

here is a demo on how to use the struct_pb protoc plugin.

I test with the latest struct_pb (commit 5272b07651accec0ed58944a031633864c48fa73) on CentOS 7. the protobuf version is
```
protoc --version
libprotoc 3.21.12
```
to use struct_pb, the protobuf must be installed first
then build struct_pb
```
git clone https://github.com/alibaba/yalantinglibs.git
cd yalantinglibs
mkdir build && cd build
cmake .. -G Ninja
ninja
```
configure log is here. you can see `BUILD_STRUCT_PB: ON`
```
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- -------------INSTALL SETTING-------------
-- INSTALL_THIRDPARTY: ON
-- INSTALL_INDEPENDENT_THIRDPARTY: ON
-- -------------COMPILE SETTING-------------
-- CXX Standard: 20
-- Build type: Release
-- BUILD_WITH_LIBCXX: OFF
-- ENDIAN: LITTLE
-- USE_CCACHE: OFF
-- -------------DEVELOP SETTING-------------
-- BUILD_EXAMPLES: ON
-- BUILD_BENCHMARK: ON
-- BUILD_UNIT_TESTS: ON
-- COVERAGE_TEST: OFF
-- GENERATE_BENCHMARK_DATA: ON
-- CORO_RPC_USE_OTHER_RPC: OFF
-- -------------PROJECT SETTING-------------
-- ENABLE_SSL: OFF
-- ENABLE_PMR: OFF
-- ENABLE_IO_URING: OFF
-- ENABLE_STRUCT_PACK_UNPORTABLE_TYPE: OFF
-- ENABLE_STRUCT_PACK_OPTIMIZE: OFF
-- BUILD_CORO_HTTP: ON
-- BUILD_CORO_IO: ON
-- BUILD_CORO_RPC: ON
-- BUILD_EASYLOG: ON
-- BUILD_INCLUDE: ON
-- BUILD_STRUCT_JSON: ON
-- BUILD_STRUCT_PACK: ON
-- BUILD_STRUCT_PB: ON
-- BUILD_STRUCT_XML: ON
-- BUILD_STRUCT_YAML: ON
-- BUILD_UTIL: ON
-- Protobuf_FOUND: TRUE
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.21.12")
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /root/yalantinglibs/build
```
after build success, the protoc plugin is in `output/bin/protoc-gen-struct_pb`
now you can use the plugin `protoc-gen-struct_pb`
assume we are in `/root/yalantinglibs/build` and a `.proto` file copy from struct_pb examples

```
cp ../src/struct_pb/examples/addressbook.proto .
```
then run the `protoc --plugin=path/to/protoc-gen-struct_pb --struct_pb_out . xxx.proto`
here, we run
```
protoc --plugin=output/bin/protoc-gen-struct_pb --struct_pb_out . addressbook.proto
```

and two files generated. `addressbook.struct_pb.cc ` and  `addressbook.struct_pb.h`
```
#ls
addressbook.proto  addressbook.struct_pb.cc  addressbook.struct_pb.h  build.ninja  cmake  CMakeCache.txt  CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  output  src

```
now you can add these two file in your srcs
