### ISSUE TITLE
Why not try to keep the RPC protocol compatible

### ISSUE THREAD

**Issue by QuantRokkie** [alibaba/yalantinglibs#554]
It is difficult to understand that the RPC communication protocol header will be modified to cause incompatibility when there are reserved bits and protocol version numbers。As an infrastructure, the RPC protocol is not compatible, means we can no longer update the ylt library。

**Comment by qicosmos** [comment]
Sorry for that, we don't know how many users depend on coro_rpc, and now way to get user feedback.
We will give a solution for the break change.

I created a dicord channel of yalantinglibs, could you join it?

We hope all ylt users can join the channel, because we can get feedbacks immediately, especially when we have to do some break changes.

**Comment by QuantRokkie** [comment]
Sure, I'll join

**Comment by qicosmos** [comment]
@QuantRokkie  We will revert the response header as before to avoid the break change.
